# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7eb7e5e6d0d61f150a432621708c388c44d0bfef21fb73be34ea2dd76d884131350da9b57b44b6dd0bb337a0f17842611185b575e383099d9c3a46913d903b5

test:
  secret_key_base: 043a6029208cfee703b9028ad17154326b90515937c9324f530e420f1d9647921267dcbe8a6026e6d21f7ef4e13ec0c75c40c180be95b8a5eae163e755510191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
